SELECT CITY.NAME
FROM CITY
JOIN COUNTRY
ON CITY.CountryCode = COUNTRY.Code 
WHERE CONTINENT = 'Africa';

--SELECT NAME
--FROM CITY
--WHERE COUNTRYCODE IN(
--    SELECT CODE 
--    FROM COUNTRY
--    WHERE CONTINENT = 'Africa'
--);
