SELECT 
    c.COMPANY_CODE, 
    c.FOUNDER,
    COUNT(DISTINCT e.LEAD_MANAGER_CODE),
    COUNT(DISTINCT e.SENIOR_MANAGER_CODE),
    COUNT(DISTINCT e.MANAGER_CODE),
    COUNT(DISTINCT e.EMPLOYEE_CODE)
FROM COMPANY c
JOIN EMPLOYEE e
    ON c.COMPANY_CODE = e.COMPANY_CODE
GROUP BY c.COMPANY_CODE, c.FOUNDER
ORDER BY c.COMPANY_CODE;
