-- METHOD1

--SELECT SUM(POPULATION)
--FROM CITY
--WHERE COUNTRYCODE IN(
--    SELECT CODE 
--    FROM COUNTRY
--    WHERE Continent = 'Asia'
--)

--METHOD2
--SELECT SUM(CITY.POPULATION)
--FROM CITY
--JOIN COUNTRY
--ON CITY.COUNTRYCODE = COUNTRY.CODE
--WHERE COUNTRY.Continent = 'Asia'
