--Method 1
--SELECT DISTINCT CITY
--FROM STATION
--WHERE
--    CITY NOT LIKE 'a%' AND CITY NOT LIKE 'i%' AND CITY NOT LIKE 'e%' 
--    AND CITY NOT LIKE 'u%' and CITY NOT LIKE 'o%';
--Method2

SELECT DISTINCT CITY
FROM STATION
WHERE LEFT(CITY, 1) NOT IN ('a', 'e', 'i', 'o', 'u');
