-- MYSQL

(SELECT CITY, LENGTH(CITY)
FROM STATION
ORDER BY LENGTH(CITY) ASC, CITY ASC
LIMIT 1)

UNION

(SELECT CITY, LENGTH(CITY)
FROM STATION
ORDER BY LENGTH(CITY) DESC, CITY ASC
LIMIT 1)

-- SQL SERVER

SELECT CITY, LEN(CITY)
FROM (
    SELECT TOP 1 CITY, LEN(CITY) AS L
    FROM STATION
    ORDER BY LEN(CITY) ASC, CITY ASC
) AS A
UNION
SELECT CITY, LEN(CITY)
FROM (
    SELECT TOP 1 CITY, LEN(CITY) AS L
    FROM STATION
    ORDER BY LEN(CITY) DESC, CITY ASC
) AS B;
